[versions]
androidGradle = "8.13.1"
guava = "28.1-jre"
omniPlugin = "0.4.5"
compileSdk = "33"
minSdk = "29"
targetSdk = "33"
junitJupiter = "6.0.1"

[libraries]
chartizate = { group = "org.jesperancinha.itf", name= "itf-chartizate-java", version = "5.0.0" }
junitJupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitJupiter" }
junitJupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter" }
junitJupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitJupiter" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "6.0.1" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "androidGradle" }
jacoco = { id = "jacoco" }
omni = { id = "org.jesperancinha.plugins.omni", version.ref = "omniPlugin" }
